// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0dwNyD-fLFaXtYY3taLTh32tYSL1Xjg',
    appId: '1:722672109804:web:9acf28513a1dd5871bfdc9',
    messagingSenderId: '722672109804',
    projectId: 'bankingapp-128a7',
    authDomain: 'bankingapp-128a7.firebaseapp.com',
    storageBucket: 'bankingapp-128a7.firebasestorage.app',
    measurementId: 'G-NTDDN62FG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBVL9WJAtivvBaKJWkZY74N5sXhioMLFg',
    appId: '1:722672109804:android:dbd3865b770f65851bfdc9',
    messagingSenderId: '722672109804',
    projectId: 'bankingapp-128a7',
    storageBucket: 'bankingapp-128a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdrOjU0yAWtbC4SylC3ycaBzkKzlrybA',
    appId: '1:722672109804:ios:67b14f487d97ed501bfdc9',
    messagingSenderId: '722672109804',
    projectId: 'bankingapp-128a7',
    storageBucket: 'bankingapp-128a7.firebasestorage.app',
    iosBundleId: 'com.example.basicBanking',
  );
}
